%% SCRIPT QUI ASSOCIE UN PARTICIPANT AVEC LES BONNES ASSOCIATIONS SENSORS - MUSCLES


switch Participant{1}
    
    case 'CTL_01'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_02' % Pas TAdist
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_8_EMG8', ...
            'EMG_SOL', 'Sensor_9_EMG9', ...
            'EMG_GM', 'Sensor_10_EMG10', ...
            'EMG_VL', 'Sensor_11_EMG11', ...
            'EMG_RF', 'Sensor_12_EMG12', ...
            'EMG_ST', 'Sensor_13_EMG13', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_SOL', 'Sensor_2_EMG2', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_6_EMG6', ...
            'EMG_GMED', 'Sensor_15_EMG15');

    case 'CTL_03' % Pas TAdist
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_SOL', 'Sensor_2_EMG2', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_6_EMG6', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_SOL', 'Sensor_10_EMG10', ...
            'EMG_GM', 'Sensor_11_EMG11', ...
            'EMG_VL', 'Sensor_12_EMG12', ...
            'EMG_RF', 'Sensor_13_EMG13', ...
            'EMG_ST', 'Sensor_14_EMG14', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_04'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_05' % Pas GMED
         sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_8_EMG8');

    case 'CTL_06' % Pas GMED
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_8_EMG8');
    
    case 'CTL_07' % Pas GMED
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_8_EMG8', ...
            'EMG_TAdist', 'Sensor_9_EMG9', ...
            'EMG_SOL', 'Sensor_10_EMG10', ...
            'EMG_GM', 'Sensor_11_EMG11', ...
            'EMG_VL', 'Sensor_12_EMG12', ...
            'EMG_RF', 'Sensor_13_EMG13', ...
            'EMG_ST', 'Sensor_14_EMG14');

    case 'CTL_08' % Pas GMED
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_8_EMG8', ...
            'EMG_TAdist', 'Sensor_9_EMG9', ...
            'EMG_SOL', 'Sensor_10_EMG10', ...
            'EMG_GM', 'Sensor_11_EMG11', ...
            'EMG_VL', 'Sensor_12_EMG12', ...
            'EMG_RF', 'Sensor_13_EMG13', ...
            'EMG_ST', 'Sensor_14_EMG14');

    case 'CTL_09'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_10'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_11'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_12'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_13'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_14'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

    case 'CTL_15'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_16'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_17'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_18'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_19'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_20'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_21'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_22'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_23'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_24'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_25'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_14_EMG14', ...
            'EMG_RF', 'Sensor_13_EMG13', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_26'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_27'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_2_EMG2', ...
            'EMG_TAdist', 'Sensor_1_EMG1', ...
            'EMG_SOL', 'Sensor_3_EMG3', ...
            'EMG_GM', 'Sensor_4_EMG4', ...
            'EMG_VL', 'Sensor_5_EMG5', ...
            'EMG_RF', 'Sensor_6_EMG6', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_28'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_29'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_30'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_31'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_32'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_33'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_34'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_35'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_36'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_37'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_38'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');
    
    case 'CTL_39'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_40'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_41'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

    case 'CTL_42'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_43'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_44'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_45'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_46'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_47'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_48'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_49'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_50'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_51'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_52'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_53'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_54'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_55'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_56'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_57'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_58'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_59'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_60'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_61'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_62'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_1_EMG1', ...
            'EMG_TAdist', 'Sensor_2_EMG2', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_8_EMG8');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_11_EMG11', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_16_EMG16');

        case 'CTL_63'
        sensor_association_left = struct( ...
            'EMG_TAprox', 'Sensor_2_EMG2', ...
            'EMG_TAdist', 'Sensor_8_EMG8', ...
            'EMG_SOL', 'Sensor_6_EMG6', ...
            'EMG_GM', 'Sensor_3_EMG3', ...
            'EMG_VL', 'Sensor_4_EMG4', ...
            'EMG_RF', 'Sensor_5_EMG5', ...
            'EMG_ST', 'Sensor_7_EMG7', ...
            'EMG_GMED', 'Sensor_1_EMG1');

        sensor_association_right = struct( ...
            'EMG_TAprox', 'Sensor_9_EMG9', ...
            'EMG_TAdist', 'Sensor_10_EMG10', ...
            'EMG_SOL', 'Sensor_16_EMG16', ...
            'EMG_GM', 'Sensor_12_EMG12', ...
            'EMG_VL', 'Sensor_13_EMG13', ...
            'EMG_RF', 'Sensor_14_EMG14', ...
            'EMG_ST', 'Sensor_15_EMG15', ...
            'EMG_GMED', 'Sensor_11_EMG11');

    otherwise
        error(['Aucune correspondance capteur-muscle définie pour ' Participant{1}]);
end